spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/statistics_db?authSource=admin

app:
  kafka:
    kafkaEventTopic: "event-topic"
    kafkaEventGroupId: "kafka-event-group-id"
server:
  port:
    8082